CREATE TABLE `user` (
  `userID` int(11) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `firstName` varchar(255) NOT NULL,
  `lastName` varchar(255) NOT NULL,
  `dob` date DEFAULT NULL,
  `gender` enum('Male','Female','Other','NULL') DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `profilephotoURL` varchar(255) DEFAULT NULL,
  `privacyID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
